Repository zoria-lang/zoria-compiler, pull requests merged in 2020-07, with the labels that each got.

#14 Changed TypeSig to Type in some places.
  src/Syntax.hs
Labels: bug, invalid

#16 Feature/testing
  README.md
  app/Main.hs
  src/GetOpt.hs
  src/GetOpt/Internal.hs
  test/unit/GetOptTests.hs
  test/unit/Main.hs
  zoria-lang.cabal
Labels: enhancement, help wanted

#15 Feature/evaluator
  src/Evaluator.hs
  src/Evaluator/Environment.hs
  src/Evaluator/ValueSyntax.hs
  src/Syntax.hs
  zoria-lang.cabal
Labels: enhancement
